---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: my-go-app
  template:
    metadata:
      labels:
        name: my-go-app
    spec:
      containers:
      - name: application
        image: your_docker_hub_account/my-go-app:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: dockerhub-secret
        ports:
          - containerPort: 3000